name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build API image
        run: |
          docker build \
            -f src/ToDoList.Api/Dockerfile \
            -t akobirdocker/todolist-api:latest \
            .

      - name: Build Blazor image
        run: |
          docker build \
            -f src/ToDoList.BlazorUI/Dockerfile \
            -t akobirdocker/todolist-blazor:latest \
            .